// Generado por scripts/front-kit/generar.ts. No editar a mano: cambia la fuente (src/) y vuelve a generar.

/// Iconos Lucide del kit (Assets.xcassets/Iconos/ic-<nombre>).
enum Ic {
    static let arrowLeft = "arrow-left"
    static let arrowUp = "arrow-up"
    static let batteryFull = "battery-full"
    static let batteryMedium = "battery-medium"
    static let bell = "bell"
    static let bluetooth = "bluetooth"
    static let bookOpen = "book-open"
    static let briefcaseBusiness = "briefcase-business"
    static let cake = "cake"
    static let calendarDays = "calendar-days"
    static let chartNoAxesCombined = "chart-no-axes-combined"
    static let check = "check"
    static let chevronDown = "chevron-down"
    static let chevronLeft = "chevron-left"
    static let chevronRight = "chevron-right"
    static let circleCheck = "circle-check"
    static let clock3 = "clock-3"
    static let coins = "coins"
    static let ellipsis = "ellipsis"
    static let flag = "flag"
    static let handCoins = "hand-coins"
    static let handHeart = "hand-heart"
    static let house = "house"
    static let info = "info"
    static let library = "library"
    static let lightbulb = "lightbulb"
    static let list = "list"
    static let messagesSquare = "messages-square"
    static let partyPopper = "party-popper"
    static let pause = "pause"
    static let pencil = "pencil"
    static let personStanding = "person-standing"
    static let piggyBank = "piggy-bank"
    static let play = "play"
    static let puzzle = "puzzle"
    static let rotateCcw = "rotate-ccw"
    static let rotateCw = "rotate-cw"
    static let settings = "settings"
    static let shoppingCart = "shopping-cart"
    static let signal = "signal"
    static let sparkles = "sparkles"
    static let star = "star"
    static let target = "target"
    static let trash2 = "trash-2"
    static let userRound = "user-round"
    static let userRoundPlus = "user-round-plus"
    static let usersRound = "users-round"
    static let volume2 = "volume-2"
    static let wallet = "wallet"
    static let wifi = "wifi"
    static let x = "x"
}
