// Generado por scripts/front-kit/generar.ts. No editar a mano: cambia la fuente (src/) y vuelve a generar.

/// Variables de cada texto, en el orden posicional de Localizable.strings (%1$@, %2$@…).
let textoArgs: [String: [String]] = [
    "comun.verTodas": ["count"],
    "comun.estasViendo": ["nombre"],
    "comun.tituloPestana": ["titulo"],
    "dinero.errorMaximo": ["monto"],
    "dinero.errorNoAlcanza": ["monto"],
    "dinero.errorMetaNoAlcanza": ["meta", "monto"],
    "conexion.etiqueta": ["estado"],
    "alcancia.etiquetaSaldo": ["nombre"],
    "alcancia.metaVaciaTitulo": ["nombre"],
    "alcancia.borrador": ["monto"],
    "alcancia.recordatorio": ["dia"],
    "alcancia.estaSemana": ["monto"],
    "meta.avance": ["meta", "porcentaje"],
    "meta.deObjetivo": ["guardado", "objetivo"],
    "meta.detalleDe": ["objetivo"],
    "meta.detalleAvance": ["porcentaje"],
    "meta.faltan": ["porcentaje", "monto"],
    "meta.borrarConfirmar": ["meta"],
    "nuevaMeta.pregunta": ["nombre"],
    "movimientos.mesTotales": ["entro", "salio"],
    "flujo.paso": ["actual", "total"],
    "flujo.metaAlcanzada": ["meta"],
    "flujo.in.ahora": ["nombre", "monto"],
    "flujo.out.ahora": ["nombre", "monto"],
    "flujo.nino": ["nombre"],
    "flujo.recordarTitulo": ["dia"],
    "flujo.recordarListo": ["dia"],
    "aprender.enCurso": ["tema"],
    "aprender.paraEmpezar": ["tema"],
    "aprender.ahora": ["paso"],
    "aprender.felicitar": ["nombre"],
    "aprender.terminaron": ["actividad"],
    "biblioteca.minutos": ["tema", "minutos"],
    "biblioteca.jugadores": ["tema", "jugadores"],
    "biblioteca.vacio": ["formato"],
    "actividad.enCurso": ["tema"],
    "actividad.paraEmpezar": ["tema"],
    "actividad.paso": ["actual", "total"],
    "actividad.minutos": ["minutos"],
    "actividad.terminada": ["actividad"],
    "actividad.verSiguiente": ["actividad"],
    "actividad.terminadaCeja": ["tema"],
    "mision.ceja": ["tema"],
    "juego.ceja": ["jugadores"],
    "progreso.momentoDe": ["nombre"],
    "progreso.loConto": ["autor"],
    "nuevoMomento.pregunta": ["nombre"],
    "felicitar.titulo": ["nombre"],
    "chanchito.titulo": ["nombre"],
    "chanchito.bateriaDato": ["porcentaje", "cuando"],
    "chanchito.perfil": ["nombre"],
    "recordatorio.filaDia": ["dia"],
]
