// Generado por scripts/front-kit/generar.ts. No editar a mano: cambia la fuente (src/) y vuelve a generar.
package pe.alcancia.ui.plataforma

/** es.json aplanado: solo para renderizar el kit en escritorio. En Android se leen de strings.xml. */
val TEXTOS_ES: Map<String, String> = mapOf(
    "comun.app" to "Alcancía",
    "comun.continuar" to "Continuar",
    "comun.guardar" to "Guardar",
    "comun.volver" to "Volver",
    "comun.cancelar" to "Cancelar",
    "comun.cerrar" to "Cerrar",
    "comun.unRatito" to "Un ratito…",
    "comun.verTodas" to "Ver todas ({count})",
    "comun.verTodos" to "Ver todos",
    "comun.verTodo" to "Ver todo",
    "comun.verMas" to "Ver más",
    "comun.noEncontrado" to "No encontramos esto.",
    "comun.noEncontradoContenido" to "No encontramos esto. Puede que ya no esté.",
    "comun.tu" to "Tú",
    "comun.ninguna" to "Ninguna",
    "comun.noSabemos" to "No sabemos",
    "comun.ajustesChanchito" to "Ajustes del chanchito",
    "comun.estasViendo" to "Estás viendo a {nombre}. Cambiar",
    "comun.tituloPestana" to "{titulo} · Alcancía",
    "comun.deshacer" to "Deshacer",
    "comun.editar" to "Editar",
    "comun.corregir" to "Corregir",
    "comun.borrar" to "Borrar",
    "comun.guardarCambios" to "Guardar cambios",
    "comun.cambiosGuardados" to "Cambios guardados",
    "nav.etiqueta" to "Navegación principal",
    "nav.alcancia" to "Alcancía",
    "nav.aprender" to "Aprender",
    "nav.progreso" to "Progreso",
    "fechas.hoy" to "hoy",
    "fechas.ayer" to "ayer",
    "fechas.meses" to "ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic",
    "fechas.dias" to "domingo,lunes,martes,miércoles,jueves,viernes,sábado",
    "fechas.mesesLargos" to "enero,febrero,marzo,abril,mayo,junio,julio,agosto,setiembre,octubre,noviembre,diciembre",
    "dinero.errorVacio" to "Escribe cuánto.",
    "dinero.errorSeparador" to "Usa solo un punto para los céntimos.",
    "dinero.errorDecimales" to "Pon máximo dos números para los céntimos.",
    "dinero.errorFormato" to "Escribe un monto como 10 o 10.50.",
    "dinero.errorCero" to "Tiene que ser más de S/ 0.",
    "dinero.errorMaximo" to "Lo máximo es {monto}.",
    "dinero.errorNoAlcanza" to "No le alcanza: ahora tiene {monto}.",
    "dinero.errorMetaNoAlcanza" to "Para «{meta}» solo tiene {monto}.",
    "conexion.conectado" to "Conectado",
    "conexion.sinConexion" to "Sin conexión",
    "conexion.etiqueta" to "Chanchito: {estado}. Ver ajustes",
    "conexion.estadoConectado" to "conectado",
    "conexion.estadoSinConexion" to "sin conexión",
    "conexion.conectar" to "Conectar chanchito",
    "alcancia.etiquetaSaldo" to "Lo que {nombre} lleva ahorrado",
    "alcancia.llevaAhorrado" to "LLEVA AHORRADO",
    "alcancia.primeraPlata" to "Guardar su primera plata",
    "alcancia.agregarPlata" to "Agregar plata",
    "alcancia.sacarPlata" to "Sacar plata",
    "alcancia.susMetas" to "Sus metas",
    "alcancia.metaVaciaTitulo" to "¿Para qué quiere ahorrar {nombre}?",
    "alcancia.metaVaciaTexto" to "Un juguete, un libro o algo que le guste mucho. Escójanlo juntos.",
    "alcancia.metaVaciaBoton" to "Poner su primera meta",
    "alcancia.loUltimo" to "Lo último que entró y salió",
    "alcancia.vacioTitulo" to "Todavía no ha entrado ni salido plata",
    "alcancia.vacioTexto" to "Cuando agreguen o saquen plata, aparecerá aquí.",
    "alcancia.valorPrimerDia" to "Aquí ven la plata que {nombre} mete o saca de su chanchito, y cómo va creciendo.",
    "alcancia.borrador" to "Dejaron a medias: {monto}",
    "alcancia.borradorSeguir" to "Seguir",
    "alcancia.borradorDescartar" to "Descartar",
    "alcancia.recordatorio" to "Hoy es {dia}, día de su propina. ¿Ya la guardó?",
    "alcancia.recordatorioBoton" to "Guardar su propina",
    "alcancia.estaSemana" to "Esta semana: +{monto}",
    "alcancia.saltar" to "Hacer saltar al chanchito",
    "meta.logrado" to "¡Logrado!",
    "meta.avance" to "Avance de {meta}: {porcentaje}%",
    "meta.deObjetivo" to "{guardado} de {objetivo}",
    "meta.detalleVolver" to "Sus metas",
    "meta.noEncontradaTitulo" to "No encontramos esta meta",
    "meta.noEncontradaTexto" to "Puede que se hayan borrado los datos.",
    "meta.detalleDe" to "de {objetivo}",
    "meta.detalleAvance" to "Avance: {porcentaje}%",
    "meta.lograda" to "¡Lo lograron! Conversen juntos qué hacer ahora.",
    "meta.faltan" to "Va {porcentaje}% · Le faltan {monto}",
    "meta.agregar" to "Agregar plata a esta meta",
    "meta.movimientosTitulo" to "Lo que han guardado para esta meta",
    "meta.movimientosVacio" to "Todavía no han guardado plata para esta meta.",
    "meta.listaTitulo" to "Sus metas",
    "meta.listaVacia" to "Todavía no tiene metas.",
    "meta.otraMeta" to "Poner otra meta",
    "meta.enCamino" to "En camino",
    "meta.logradas" to "Logradas",
    "meta.usada" to "Ya la usaron",
    "meta.usadaTexto" to "Ya usaron esta plata. ¡Qué bien que lo lograron juntos!",
    "meta.usar" to "Usar esta plata",
    "meta.editar" to "Editar meta",
    "meta.borrar" to "Borrar meta",
    "meta.borrarConfirmar" to "¿Borrar «{meta}»? La plata guardada no se borra: sigue en lo que lleva ahorrado.",
    "meta.borrada" to "Meta borrada",
    "meta.editarTitulo" to "Editar meta",
    "nuevaMeta.tituloPrimera" to "Su primera meta",
    "nuevaMeta.tituloOtra" to "Otra meta",
    "nuevaMeta.pregunta" to "¿Para qué quiere ahorrar {nombre}?",
    "nuevaMeta.ayuda" to "Un juguete, un libro o algo que le guste mucho.",
    "nuevaMeta.nombre" to "¿Qué quiere?",
    "nuevaMeta.nombreEjemplo" to "Por ejemplo: una pelota",
    "nuevaMeta.nombreError" to "Escribe qué quiere.",
    "nuevaMeta.costo" to "¿Cuánto cuesta más o menos? (S/)",
    "nuevaMeta.guardar" to "Guardar meta",
    "movimientos.titulo" to "Lo que entró y salió",
    "movimientos.vacio" to "Todavía no ha entrado ni salido plata.",
    "movimientos.in" to "Guardó plata",
    "movimientos.out" to "Sacó plata",
    "movimientos.entro" to "Entró",
    "movimientos.salio" to "Salió",
    "movimientos.loAnoto" to "Lo hizo",
    "movimientos.cuando" to "Cuándo",
    "movimientos.porQue" to "Por qué",
    "movimientos.meta" to "Meta",
    "movimientos.leEnvio" to "Le envió",
    "movimientos.de" to "De {quien}",
    "movimientos.mesTotales" to "Entró {entro} · Salió {salio}",
    "movimientos.corregir" to "Corregir",
    "movimientos.borrar" to "Borrar",
    "movimientos.borrarConfirmar" to "¿Borrar este movimiento? Lo que lleva ahorrado se va a ajustar.",
    "movimientos.borrado" to "Borrado",
    "movimientos.borrarNoSePuede" to "No se puede borrar: después sacaron plata y quedaría en negativo. Primero corrige esa salida.",
    "movimientos.editarTitulo" to "Corregir",
    "movimientos.editarNegativo" to "Con este cambio quedaría en negativo. Revisa el monto.",
    "movimientos.editarPie" to "Lo que lleva ahorrado y sus metas se ajustan solos.",
    "flujo.paso" to "Paso {actual} de {total} · {etiqueta}",
    "flujo.pasoCuanto" to "Cuánto",
    "flujo.pasoDeDonde" to "De dónde salió",
    "flujo.pasoListo" to "Listo",
    "flujo.ahoraTieneAhorrado" to "Ahora tiene ahorrado",
    "flujo.cuanto" to "Cuánto",
    "flujo.tocaMonto" to "Toca el monto para cambiarlo.",
    "flujo.rapido" to "O escoge uno rápido",
    "flujo.asiQuedaria" to "Así quedaría",
    "flujo.pieCuanto" to "Todavía no cambia nada.",
    "flujo.escogeOpcion" to "Escoge una opción",
    "flujo.otroCampo" to "Cuéntanos qué fue",
    "flujo.ningunaMeta" to "Ninguna meta en especial",
    "flujo.pieDeDonde" to "Todavía no cambia nada.",
    "flujo.revisarCuanto" to "Cuánto",
    "flujo.revisarPorQue" to "Por qué",
    "flujo.revisarMeta" to "Meta",
    "flujo.pieRevisar" to "Recién cambia cuando toques el botón.",
    "flujo.metaAlcanzada" to "¡Ya juntaron todo para «{meta}»!",
    "flujo.pieListo" to "Lo verás en Alcancía.",
    "flujo.volverAlcancia" to "Volver a Alcancía",
    "flujo.salirConfirmar" to "Si sales ahora, no cambia nada. ¿Quieres salir?",
    "flujo.in.titulo" to "Agregar plata",
    "flujo.in.pregunta" to "¿Cuánto va a guardar?",
    "flujo.in.sub" to "Lo que {nombre} va a meter a su chanchito.",
    "flujo.in.deDonde" to "¿De dónde salió esta plata?",
    "flujo.in.resumen" to "{nombre} va a guardar {monto}.",
    "flujo.in.paraMeta" to "¿Es para alguna meta?",
    "flujo.in.sinMeta" to "Se suma a lo que ya tiene ahorrado.",
    "flujo.in.ahora" to "Ahora {nombre} lleva ahorrado {monto}.",
    "flujo.in.confirmar" to "Sí, guardar",
    "flujo.in.listo" to "¡Listo, ya se guardó!",
    "flujo.out.titulo" to "Sacar plata",
    "flujo.out.pregunta" to "¿Cuánto va a sacar?",
    "flujo.out.sub" to "Lo que {nombre} va a sacar de su chanchito.",
    "flujo.out.deDonde" to "¿En qué la va a usar?",
    "flujo.out.resumen" to "{nombre} va a sacar {monto}.",
    "flujo.out.paraMeta" to "¿Sale de alguna meta?",
    "flujo.out.sinMeta" to "No sale de ninguna meta.",
    "flujo.out.ahora" to "Ahora {nombre} tiene {monto}.",
    "flujo.out.confirmar" to "Sí, sacar",
    "flujo.out.listo" to "¡Listo, ya se sacó!",
    "flujo.pasoQuien" to "Quién envía",
    "flujo.pasoEnQue" to "En qué",
    "flujo.revisarQuien" to "Quién envía",
    "flujo.resumen" to "Resumen",
    "flujo.nino" to "¿Y si {nombre} mete la moneda? Que toque el chanchito.",
    "flujo.ninoBoton" to "Meter la moneda al chanchito",
    "flujo.ninoListo" to "¡Clin! Adentro.",
    "flujo.recordarTitulo" to "¿Te recordamos los {dia} guardar su propina?",
    "flujo.recordarSi" to "Sí, recuérdame",
    "flujo.recordarNo" to "Ahora no",
    "flujo.recordarListo" to "Listo. Los {dia} te lo recordamos en Alcancía.",
    "motivos.mesada" to "Su propina de la semana",
    "motivos.ayuda-en-casa" to "Ayudó en casa",
    "motivos.cumpleanos" to "Por su cumple",
    "motivos.propina" to "Le dieron propina",
    "motivos.buen-comportamiento" to "Se portó bien",
    "motivos.otro" to "Otra cosa",
    "motivos.compra" to "Se compró algo",
    "motivos.regalo" to "Hizo un regalo",
    "motivos.compartir" to "Lo compartió",
    "temas.ahorrar" to "Ahorrar",
    "temas.gastar-bien" to "Gastar bien",
    "temas.compartir" to "Compartir",
    "temas.ganar" to "Ganar",
    "temas.todos" to "Todos los temas",
    "temas.yaEmpezaron" to "Ya empezaron",
    "temas.todaviaNo" to "Todavía no empiezan",
    "aprender.titulo" to "Aprender",
    "aprender.bienvenida" to "Aprendan a ahorrar juntos",
    "aprender.bienvenidaTexto" to "Explora ideas para acompañar a {nombre}. No necesitas saber de finanzas.",
    "aprender.enCurso" to "EN CURSO · {tema}",
    "aprender.paraEmpezar" to "PARA EMPEZAR · {tema}",
    "aprender.ahora" to "Ahora: {paso}",
    "aprender.seguir" to "Seguir con la actividad",
    "aprender.verDeQue" to "Ver de qué se trata",
    "aprender.otrasCosas" to "Otras cosas que pueden hacer",
    "aprender.otrasFormas" to "Otras formas de acompañar",
    "aprender.cuandoQuieran" to "Cuando quieran. No son tareas.",
    "aprender.aSuRitmo" to "A su ritmo. Ustedes escogen por dónde empezar.",
    "aprender.biblioteca" to "Biblioteca",
    "aprender.bibliotecaTexto" to "Cuentos, misiones y juegos.",
    "aprender.anotar" to "Contar algo que pasó",
    "aprender.anotarTexto" to "Algo bonito que {nombre} dijo o hizo.",
    "aprender.felicitar" to "Felicitar a {nombre}",
    "aprender.felicitarTexto" to "Un mensajito por su esfuerzo.",
    "aprender.terminaron" to "Ya terminaron «{actividad}». ¿Siguen con otra?",
    "aprender.todasTerminadas" to "Ya hicieron todas las actividades. Pueden repetir la que quieran o escoger algo de la Biblioteca.",
    "biblioteca.titulo" to "Biblioteca",
    "biblioteca.volver" to "Aprender",
    "biblioteca.formato" to "Formato",
    "biblioteca.cuentos" to "Cuentos",
    "biblioteca.misiones" to "Misiones",
    "biblioteca.juegos" to "Juegos",
    "biblioteca.subCuentos" to "Escojan lo que quieran, en el orden que quieran.",
    "biblioteca.subMisiones" to "Cositas para hacer juntos en casa.",
    "biblioteca.subJuegos" to "Jueguen a ser otros y conversen.",
    "biblioteca.cejaCuento" to "EL CUENTO DEL CHANCHITO",
    "biblioteca.cejaMision" to "PARA HACER EN CASA",
    "biblioteca.cejaJuego" to "IMAGINEN Y CONVERSEN",
    "biblioteca.ctaCuento" to "Escuchar en el chanchito",
    "biblioteca.ctaMision" to "Ver misión",
    "biblioteca.ctaJuego" to "Ver juego",
    "biblioteca.masParaVer" to "Más para ver",
    "biblioteca.filtrar" to "Filtrar por tema",
    "biblioteca.minutos" to "{tema} · {minutos} min",
    "biblioteca.jugadores" to "{tema} · {jugadores}",
    "biblioteca.vacio" to "Todavía no hay {formato} de este tema.",
    "actividad.titulo" to "Actividad",
    "actividad.noEncontrada" to "No encontramos esta actividad.",
    "actividad.enCurso" to "EN CURSO · {tema}",
    "actividad.paraEmpezar" to "PARA EMPEZAR · {tema}",
    "actividad.loQueVan" to "Lo que van a hacer",
    "actividad.loQueVanTexto" to "En el orden que quieran. Si no terminan hoy, siguen otro día.",
    "actividad.tocaAhora" to "Toca ahora",
    "actividad.yaHicimos" to "Ya hicimos este paso",
    "actividad.ultimoPaso" to "¡Ya están en el último paso! Pueden repetir lo que quieran o {enlace} cuando quieran.",
    "actividad.verOtroTema" to "ver otro tema",
    "actividad.noLaEmpieza" to "Mirar esto no la empieza. Empiecen cuando quieran.",
    "actividad.pieEmpezada" to "Pueden seguir otro día.",
    "actividad.pieNueva" to "La pueden dejar cuando quieran.",
    "actividad.seguir" to "Seguir con la actividad",
    "actividad.empezar" to "Empezar",
    "actividad.verActividad" to "Ver la actividad",
    "actividad.paso" to "PASO {actual} DE {total}",
    "actividad.minutos" to "{minutos} min",
    "actividad.terminar" to "Ya terminamos",
    "actividad.terminada" to "¡Terminaron «{actividad}»!",
    "actividad.terminadaTexto" to "Sin apuro. Cuando quieran, prueben otra:",
    "actividad.terminadaTodas" to "Ya hicieron todas. Pueden repetir la que quieran.",
    "actividad.verSiguiente" to "Ver «{actividad}»",
    "actividad.terminadaCeja" to "YA LA HICIERON · {tema}",
    "tema.titulo" to "Tema",
    "tema.noEncontrado" to "No encontramos este tema.",
    "tema.volver" to "Progreso",
    "tema.anotado" to "Lo que han contado",
    "tema.anotadoVacio" to "Todavía no han contado nada de este tema. Es opcional.",
    "tema.anotar" to "Contar algo que pasó",
    "tema.actividad" to "Actividad",
    "cuento.barra" to "Aprender juntos",
    "cuento.titulo" to "Cuento",
    "cuento.sub" to "Un cuento para escuchar juntos.",
    "cuento.ceja" to "EL CUENTO",
    "cuento.enChanchito" to "Escuchar en el chanchito",
    "cuento.enCelular" to "Escuchar en este celular",
    "cuento.posicion" to "Posición del audio",
    "cuento.atras" to "Retroceder 10 segundos",
    "cuento.adelante" to "Adelantar 10 segundos",
    "cuento.diezSegundos" to "10 s",
    "cuento.reproducir" to "Reproducir",
    "cuento.pausar" to "Pausar",
    "cuento.errorChanchito" to "El chanchito no está conectado, así que no se puede escuchar ahí. Pero pueden leer el cuento juntos.",
    "cuento.errorAudio" to "El audio todavía no está listo. Pero pueden leer el cuento juntos.",
    "cuento.despues" to "Después, conversen: {pregunta}",
    "cuento.verPreguntas" to "Ver preguntas para conversar",
    "cuento.otroDia" to "Seguir otro día",
    "cuento.versionCorta" to "Versión de 1 minuto",
    "cuento.versionCompleta" to "Cuento completo",
    "cuento.leerVoz" to "Leer en voz alta",
    "cuento.leerVozAyuda" to "Con la voz de este celular.",
    "cuento.detenerVoz" to "Detener",
    "cuento.vozNoDisponible" to "Este celular no puede leer en voz alta. Pueden leerlo juntos.",
    "cuento.sonandoChanchito" to "Está sonando en el chanchito. Pueden leer juntos mientras escuchan.",
    "guia.titulo" to "Para conversar",
    "guia.pregunta" to "Pregúntale",
    "guia.consejos" to "Unos consejos para ti",
    "guia.consejo1" to "Escucha primero. Aquí no hay respuestas buenas ni malas.",
    "guia.consejo2" to "Pregunta «¿y por qué?» con curiosidad, sin corregir.",
    "guia.consejo3" to "Si no es el momento, lo dejan para otro día. No pasa nada.",
    "guia.anotado" to "¡Listo! Gracias por darte el tiempo.",
    "guia.anotadoCorto" to "¡Listo!",
    "guia.pie" to "Marcarlo es opcional. No es una nota para nadie.",
    "guia.yaConversamos" to "Ya lo conversamos",
    "guia.volverAprender" to "Volver a Aprender",
    "mision.titulo" to "Misión",
    "mision.ceja" to "PARA HACER EN CASA · {tema}",
    "mision.necesitan" to "Van a necesitar",
    "mision.comoSeHace" to "Cómo se hace",
    "mision.noEsTarea" to "Marquen lo que van haciendo. No es tarea.",
    "mision.pie" to "Si quieren, cuenten cómo les fue.",
    "mision.anotar" to "Contar cómo les fue",
    "mision.volverBiblioteca" to "Volver a Biblioteca",
    "juego.titulo" to "Juego",
    "juego.ceja" to "IMAGINEN Y CONVERSEN · {jugadores}",
    "juego.roles" to "Quién hace qué",
    "juego.despues" to "Para conversar después",
    "progreso.titulo" to "Progreso",
    "progreso.sinNotas" to "Sin notas ni comparar con nadie",
    "progreso.estaSemana" to "ESTA SEMANA",
    "progreso.loUltimo" to "LO ÚLTIMO QUE CONTARON",
    "progreso.momentoDe" to "Un momento de {nombre}",
    "progreso.loConto" to "Lo contó {autor}",
    "progreso.vacioCeja" to "TODAVÍA NO HAN CONTADO NADA",
    "progreso.vacioTitulo" to "Cuenten lo que vean",
    "progreso.vacioTexto" to "Cuando {nombre} diga o haga algo que quieran recordar, cuéntenlo aquí. Sin apuro.",
    "progreso.anotar" to "Contar algo que pasó",
    "progreso.cosas_one" to "{count} cosa contada",
    "progreso.cosas_other" to "{count} cosas contadas",
    "progreso.conversaciones_one" to "{count} conversación",
    "progreso.conversaciones_other" to "{count} conversaciones",
    "progreso.descubriendo" to "Lo que va descubriendo",
    "progreso.queHacer" to "¿Qué pueden hacer ahora?",
    "progreso.verActividad" to "Ver la actividad",
    "progreso.todosEmpezados" to "Ya empezaron algo en todos los temas. Cuando quieran, escojan algo de la Biblioteca.",
    "progreso.abrirBiblioteca" to "Abrir Biblioteca",
    "momento.titulo" to "Lo que pasó",
    "momento.ceja" to "LO QUE PASÓ",
    "momento.noEsNota" to "Es lo que vio alguien de la familia, no una nota.",
    "momento.mensajitos" to "Mensajitos",
    "momento.pie" to "Es opcional.",
    "momento.mandarMensajito" to "Mandarle un mensajito",
    "nuevoMomento.barra" to "Contar algo que pasó",
    "nuevoMomento.pregunta" to "¿Qué dijo o hizo {nombre}?",
    "nuevoMomento.ayuda" to "Cuenta lo que viste o escuchaste, con tus palabras.",
    "nuevoMomento.quePaso" to "¿Qué pasó?",
    "nuevoMomento.quePasoError" to "Cuéntanos qué pasó.",
    "nuevoMomento.titulo" to "Título (opcional)",
    "nuevoMomento.tituloEjemplo" to "Por ejemplo: ¡Guardó su propina!",
    "nuevoMomento.quien" to "¿Quién lo vio?",
    "nuevoMomento.quienEjemplo" to "Mamá, papá, la abuela, el tío…",
    "nuevoMomento.quienError" to "Dinos quién lo vio.",
    "nuevoMomento.tema" to "Tema (opcional)",
    "nuevoMomento.sinTema" to "Ninguno en especial",
    "nuevoMomento.pie" to "Se guarda con la fecha de hoy.",
    "nuevoMomento.barraEditar" to "Editar lo que pasó",
    "nuevoMomento.borrarConfirmar" to "¿Borrar esto que contaron? También se borran sus mensajitos.",
    "nuevoMomento.borrado" to "Borrado",
    "felicitar.barra" to "Felicitar",
    "felicitar.titulo" to "Un mensajito para {nombre}",
    "felicitar.ayuda" to "Escoge una frase o escribe la tuya. Lo bonito es reconocer su esfuerzo.",
    "felicitar.etiqueta" to "Mensaje",
    "felicitar.frase1" to "¡Qué orgullo, lo hiciste muy bien!",
    "felicitar.frase2" to "¡Qué chévere cómo lo pensaste!",
    "felicitar.frase3" to "Gracias por contármelo.",
    "felicitar.frase4" to "Sigue así, a tu ritmo.",
    "felicitar.escribirMio" to "Escribir el mío",
    "felicitar.tuMensajito" to "Tu mensajito",
    "felicitar.pie" to "Es solo un mensaje bonito, no una nota.",
    "felicitar.guardado" to "¡Mensajito guardado!",
    "felicitar.volverAprender" to "Volver a Aprender",
    "avances.volver" to "Progreso",
    "avances.titulo" to "Todo lo que han contado",
    "avances.sub" to "Lo que han contado y conversado. La plata se ve en Alcancía.",
    "avances.cosas" to "Cosas que pasaron",
    "avances.cosasVacio" to "Todavía no hay nada.",
    "avances.conversaciones" to "Conversaciones",
    "avances.conversacionesVacio" to "Todavía no hay conversaciones.",
    "avances.mensajitos" to "Mensajitos",
    "avances.mensajitosVacio" to "Todavía no hay mensajitos.",
    "chanchito.titulo" to "El chanchito de {nombre}",
    "chanchito.conectando" to "Conectando…",
    "chanchito.buscando" to "Buscando el chanchito…",
    "chanchito.sinConexionTexto" to "Préndelo y revisa el WiFi de la casa.",
    "chanchito.errorConexion" to "No se pudo conectar. Préndelo, revisa el WiFi de la casa e intenta otra vez.",
    "chanchito.intentar" to "Intentar otra vez",
    "chanchito.seccion" to "El chanchito",
    "chanchito.sinConexionNota" to "Sin conexión, esto es lo último que sabemos.",
    "chanchito.bateria" to "Batería",
    "chanchito.bateriaDato" to "{porcentaje}% · {cuando}",
    "chanchito.ahoraMismo" to "Ahora",
    "chanchito.loUltimo" to "lo último que sabemos",
    "chanchito.wifi" to "Red WiFi",
    "chanchito.wifiDato" to "{red} · la que tiene guardada",
    "chanchito.volumen" to "Volumen",
    "chanchito.volumenDato" to "{porcentaje}% · lo último que sabemos",
    "chanchito.conectarCelular" to "Conectar este celular",
    "chanchito.conectarCelularTexto" to "Para manejar el chanchito desde aquí.",
    "chanchito.familia" to "Familia",
    "chanchito.perfil" to "Perfil de {nombre}",
    "chanchito.perfilTexto" to "Su nombre",
    "chanchito.cerrarSesion" to "Cerrar sesión",
    "chanchito.version" to "PiggyBank IoT · v2.4.0",
    "chanchito.reiniciarDemo" to "Reiniciar la demo",
    "chanchito.reiniciarConfirmar" to "Todo volverá a como estaba al abrir la demo. ¿Seguro?",
    "chanchito.desdeCero" to "Empezar desde cero",
    "chanchito.desdeCeroConfirmar" to "Se va a borrar todo para empezar desde cero. ¿Seguro?",
    "chanchito.avisoSinConexion" to "Sin conexión.",
    "chanchito.avisoNoAlDia" to "Esto es lo último que sabemos; no está al día.",
    "chanchito.nuncaTitulo" to "Conecten su chanchito",
    "chanchito.nuncaTexto" to "Mientras tanto, pueden llevar aquí la cuenta de su plata. Cuando lo conecten, verán su batería y él dirá quién le mandó la plata.",
    "chanchito.nuncaBoton" to "Conectar el chanchito",
    "chanchito.conectadoTexto" to "Todo bien: está prendido y conectado al WiFi de la casa.",
    "chanchito.volumenAhora" to "{porcentaje}%",
    "bateria.loUltimo" to "Lo último que sabemos",
    "bateria.sinFecha" to "No sabemos de cuándo es este dato.",
    "bateria.conecta" to "Conecta el chanchito para ver cuánta batería tiene ahora.",
    "bateria.consejos" to "Algunos consejos",
    "bateria.consejo1" to "Cárgalo cuando le quede poquita batería.",
    "bateria.consejo2" to "Si no prende, revisa el cable y el cargador.",
    "bateria.ahora" to "Ahora tiene",
    "wifi.guardado" to "WiFi guardado",
    "wifi.primero" to "Para cambiar de WiFi, primero conecta el chanchito.",
    "wifi.cambiar" to "Cambiar de WiFi",
    "wifi.reconectar" to "Para volver a conectarlo",
    "wifi.paso1" to "Prende el chanchito.",
    "wifi.paso2" to "Revisa que el WiFi de la casa esté funcionando (tiene que ser de 2.4 GHz).",
    "wifi.paso3" to "Acércalo al router (el aparato del internet) e intenta otra vez.",
    "wifi.conectadoA" to "Conectado a",
    "wifi.todoBien" to "El chanchito está usando este WiFi.",
    "volumen.loUltimo" to "Lo último que sabemos",
    "volumen.etiqueta" to "Volumen",
    "volumen.confirma" to "El volumen solo cambia cuando el chanchito lo confirme.",
    "volumen.sinConexion" to "Sin conexión no se puede cambiar el volumen.",
    "volumen.ahora" to "Ahora está en",
    "emparejar.titulo" to "Maneja el chanchito desde este celular",
    "emparejar.paso1" to "Prende el chanchito y tenlo cerca.",
    "emparejar.paso2" to "Prende el Bluetooth de este celular.",
    "emparejar.paso3" to "Toca «Buscar chanchito» y escógelo en la lista.",
    "emparejar.noSoportado" to "Desde este navegador no se puede usar Bluetooth. Prueba con Chrome en un celular Android.",
    "emparejar.noEncontrado" to "No se pudo conectar. Revisa que esté prendido y cerca, e intenta otra vez.",
    "emparejar.permiso" to "El celular te va a pedir permiso para conectarse.",
    "emparejar.buscar" to "Buscar chanchito",
    "perfil.nombre" to "Nombre",
    "perfil.nombreError" to "Escribe un nombre.",
    "perfil.ayuda" to "Así aparecerá en toda la app.",
    "perfiles.titulo" to "¿Con quién estás?",
    "perfiles.ayuda" to "Todo lo que hagas será para esta persona.",
    "perfiles.estasAqui" to "Estás aquí",
    "perfiles.editar" to "Editar perfil",
    "sesion.cerrarTitulo" to "¿Cerrar sesión?",
    "sesion.cerrarTexto" to "Puedes volver a entrar cuando quieras. Lo que guardaste en este celular no se borra.",
    "sesion.cerrada" to "Sesión cerrada",
    "sesion.cerradaTexto" to "Todavía no hay cuentas de usuario en esta versión, así que puedes entrar directo.",
    "sesion.entrar" to "Entrar de nuevo",
    "noEncontrado.titulo" to "Uy, esta página no existe",
    "noEncontrado.texto" to "Puede que el enlace esté mal. No te preocupes, todo sigue guardado.",
    "noEncontrado.boton" to "Ir a Alcancía",
    "quien.titulo" to "¿Quién le envía?",
    "quien.sub" to "Abuelos y tíos también pueden mandarle plata. Cuando el chanchito está conectado, dice su nombre en voz alta.",
    "quien.mama" to "Mamá",
    "quien.papa" to "Papá",
    "quien.abuela" to "Abuela",
    "quien.abuelo" to "Abuelo",
    "quien.tio" to "Tío o tía",
    "quien.otro" to "Otro pariente",
    "quien.admin" to "Administra la cuenta",
    "quien.otroCampo" to "¿Quién es?",
    "quien.otroEjemplo" to "Por ejemplo: Tía Rosa",
    "idea.ceja" to "IDEA DE 1 MINUTO",
    "idea.hecho" to "Ya lo hicimos",
    "idea.anotado" to "¡Listo! Gracias por darte el minuto.",
    "idea.otra" to "Otra idea",
    "acompana.fila" to "Quién acompaña",
    "acompana.filaVacia" to "Dinos quién eres",
    "acompana.titulo" to "¿Quién acompaña a {nombre}?",
    "acompana.ayuda" to "Lo usamos para saber quién hizo cada cosa y para marcar quién envía la plata.",
    "acompana.nombre" to "Tu nombre",
    "acompana.nombreEjemplo" to "Por ejemplo: Mamá, Carmen",
    "acompana.relacion" to "¿Qué eres de {nombre}?",
    "acompana.guardado" to "Guardado",
    "recordatorio.fila" to "Recordatorio de propina",
    "recordatorio.filaDia" to "Los {dia}",
    "recordatorio.filaNo" to "Sin recordatorio",
    "recordatorio.titulo" to "¿Qué día le dan su propina?",
    "recordatorio.ayuda" to "Ese día te lo recordamos al abrir Alcancía.",
    "recordatorio.ninguno" to "Sin recordatorio",
    "recordatorio.guardado" to "Recordatorio guardado",
)
