// Generado por scripts/front-kit/generar.ts. No editar a mano: cambia la fuente (src/) y vuelve a generar.
package pe.alcancia.ui.componentes

/** Iconos Lucide del kit. En Android son res/drawable/ic_<nombre>.xml; en iOS, Assets/Iconos/ic-<nombre>. */
object Ic {
    const val ArrowLeft = "arrow-left"
    const val ArrowUp = "arrow-up"
    const val BatteryFull = "battery-full"
    const val BatteryMedium = "battery-medium"
    const val Bell = "bell"
    const val Bluetooth = "bluetooth"
    const val BookOpen = "book-open"
    const val BriefcaseBusiness = "briefcase-business"
    const val Cake = "cake"
    const val CalendarDays = "calendar-days"
    const val ChartNoAxesCombined = "chart-no-axes-combined"
    const val Check = "check"
    const val ChevronDown = "chevron-down"
    const val ChevronLeft = "chevron-left"
    const val ChevronRight = "chevron-right"
    const val CircleCheck = "circle-check"
    const val Clock3 = "clock-3"
    const val Coins = "coins"
    const val Ellipsis = "ellipsis"
    const val Flag = "flag"
    const val HandCoins = "hand-coins"
    const val HandHeart = "hand-heart"
    const val House = "house"
    const val Info = "info"
    const val Library = "library"
    const val Lightbulb = "lightbulb"
    const val List = "list"
    const val MessagesSquare = "messages-square"
    const val PartyPopper = "party-popper"
    const val Pause = "pause"
    const val Pencil = "pencil"
    const val PersonStanding = "person-standing"
    const val PiggyBank = "piggy-bank"
    const val Play = "play"
    const val Puzzle = "puzzle"
    const val RotateCcw = "rotate-ccw"
    const val RotateCw = "rotate-cw"
    const val Settings = "settings"
    const val ShoppingCart = "shopping-cart"
    const val Signal = "signal"
    const val Sparkles = "sparkles"
    const val Star = "star"
    const val Target = "target"
    const val Trash2 = "trash-2"
    const val UserRound = "user-round"
    const val UserRoundPlus = "user-round-plus"
    const val UsersRound = "users-round"
    const val Volume2 = "volume-2"
    const val Wallet = "wallet"
    const val Wifi = "wifi"
    const val X = "x"
}
