// Generado por scripts/front-kit/generar.ts. No editar a mano: cambia la fuente (src/) y vuelve a generar.
package pe.alcancia.ui.i18n

/** Variables de cada texto, en el orden posicional de strings.xml (%1$s, %2$s…). */
val TEXTO_ARGS: Map<String, List<String>> = mapOf(
    "comun.verTodas" to listOf("count"),
    "comun.estasViendo" to listOf("nombre"),
    "comun.tituloPestana" to listOf("titulo"),
    "dinero.errorMaximo" to listOf("monto"),
    "dinero.errorNoAlcanza" to listOf("monto"),
    "dinero.errorMetaNoAlcanza" to listOf("meta", "monto"),
    "conexion.etiqueta" to listOf("estado"),
    "alcancia.etiquetaSaldo" to listOf("nombre"),
    "alcancia.metaVaciaTitulo" to listOf("nombre"),
    "alcancia.borrador" to listOf("monto"),
    "alcancia.recordatorio" to listOf("dia"),
    "alcancia.estaSemana" to listOf("monto"),
    "meta.avance" to listOf("meta", "porcentaje"),
    "meta.deObjetivo" to listOf("guardado", "objetivo"),
    "meta.detalleDe" to listOf("objetivo"),
    "meta.detalleAvance" to listOf("porcentaje"),
    "meta.faltan" to listOf("porcentaje", "monto"),
    "meta.borrarConfirmar" to listOf("meta"),
    "nuevaMeta.pregunta" to listOf("nombre"),
    "movimientos.mesTotales" to listOf("entro", "salio"),
    "flujo.paso" to listOf("actual", "total"),
    "flujo.metaAlcanzada" to listOf("meta"),
    "flujo.in.ahora" to listOf("nombre", "monto"),
    "flujo.out.ahora" to listOf("nombre", "monto"),
    "flujo.nino" to listOf("nombre"),
    "flujo.recordarTitulo" to listOf("dia"),
    "flujo.recordarListo" to listOf("dia"),
    "aprender.enCurso" to listOf("tema"),
    "aprender.paraEmpezar" to listOf("tema"),
    "aprender.ahora" to listOf("paso"),
    "aprender.felicitar" to listOf("nombre"),
    "aprender.terminaron" to listOf("actividad"),
    "biblioteca.minutos" to listOf("tema", "minutos"),
    "biblioteca.jugadores" to listOf("tema", "jugadores"),
    "biblioteca.vacio" to listOf("formato"),
    "actividad.enCurso" to listOf("tema"),
    "actividad.paraEmpezar" to listOf("tema"),
    "actividad.paso" to listOf("actual", "total"),
    "actividad.minutos" to listOf("minutos"),
    "actividad.terminada" to listOf("actividad"),
    "actividad.verSiguiente" to listOf("actividad"),
    "actividad.terminadaCeja" to listOf("tema"),
    "mision.ceja" to listOf("tema"),
    "juego.ceja" to listOf("jugadores"),
    "progreso.momentoDe" to listOf("nombre"),
    "progreso.loConto" to listOf("autor"),
    "nuevoMomento.pregunta" to listOf("nombre"),
    "felicitar.titulo" to listOf("nombre"),
    "chanchito.titulo" to listOf("nombre"),
    "chanchito.bateriaDato" to listOf("porcentaje", "cuando"),
    "chanchito.perfil" to listOf("nombre"),
    "recordatorio.filaDia" to listOf("dia"),
)

/** Mismo nombre que en strings.xml: «alcancia.agregarPlata» → «alcancia_agregar_plata». */
fun androidName(clave: String): String =
    clave.replace(Regex("[.-]"), "_").replace(Regex("([a-z0-9])([A-Z])"), "$1_$2").lowercase()
